FROM ubuntu:artful

RUN apt-get update -y && apt-get install -y \
    libboost-filesystem1.62.0 \
    libboost-regex1.62.0 \
    libboost-system1.62.0 \
    libczmq4 \
    libglu1-mesa \
    libzmq5

COPY ./app /app
ENV PATH=${PATH}:/app
ENTRYPOINT ["uxas"]
