apps-$(CONFIG_APP_SOI_TK1) += soi_tk1
soi_tk1: common libsel4 libmuslc libsel4vka libsel4allocman libsel4muslcsys \
libsel4vspace libsel4utils libpci libcpio libsel4vmm libelf libutils libsel4camkes libsel4sync \
libsel4debug libsel4muslccamkes libsel4simple libsel4simple-default libsel4platsupport libethdrivers liblwip