; Generated using "SADL Requirements Language to ACL2 Sedan" Translator Version 1.98
(in-package "ACL2S")
(set-ignore-ok t)
(defttag :progn!)
(include-book "requirements-analyses-book")

(defdata |translator_generated_name^rareq2_yindex| (range integer (*SRL-data-minimum* <= _ <= *SRL-data-maximum*)))
(deffconst |*translator_generated_name^rareq2_yindex-VALS*| (quote-all (gen-int-range *SRL-data-minimum* *SRL-data-maximum*)))
;(datavariable |rareq2_yindex|)

(displayname |rareq2_yindex| |rareq2_yindex|)
(displayname |rareq2_yindexP| |rareq2_yindexP|)
(displayname |translator_generated_name^rareq2_yindex| |translator generated name for rareq2_yindex|)
(displayname |translator_generated_name^rareq2_yindexP| |translator generated name for rareq2_yindexP|)
(displayname |*rareq2_yindex-VALS*| |*rareq2_yindex-VALS*|)
(displayname |*rareq2_yindex-VALUES*| |*rareq2_yindex-VALUES*|)
(displayname |*translator_generated_name^rareq2_yindex-VALS*| |*translator generated name for rareq2_yindex-VALS*|)
(displayname |*translator_generated_name^rareq2_yindex-VALUES*| |*translator generated name for rareq2_yindex-VALUES*|)

(defdata |translator_generated_name^translator_intermediate_variable_8^http://sadl.org/RequestAggregator.sadl#vi^var14| (enum '(|http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo| )))
(defdata |translator_generated_name^http://sadl.org/RequestAggregator.sadl#vi^var14| (listof |translator_generated_name^translator_intermediate_variable_8^http://sadl.org/RequestAggregator.sadl#vi^var14|))
(displayname |translator_intermediate_variable_8^http://sadl.org/RequestAggregator.sadl#vi^var14| |translator_intermediate_variable_8 of vi of var14|)
(displayname |translator_intermediate_variable_8^http://sadl.org/RequestAggregator.sadl#vi^var14P| |translator_intermediate_variable_8 of vi of var14P|)
(displayname |translator_generated_name^translator_intermediate_variable_8^http://sadl.org/RequestAggregator.sadl#vi^var14| |translator generated name for translator_intermediate_variable_8 of vi of var14|)
(displayname |translator_generated_name^translator_intermediate_variable_8^http://sadl.org/RequestAggregator.sadl#vi^var14P| |translator generated name for translator_intermediate_variable_8 of vi of var14P|)
(displayname |http://sadl.org/RequestAggregator.sadl#vi^var14| |vi of var14|)
(displayname |http://sadl.org/RequestAggregator.sadl#vi^var14P| |vi of var14P|)
(displayname |translator_generated_name^http://sadl.org/RequestAggregator.sadl#vi^var14| |translator generated name for vi of var14|)
(displayname |translator_generated_name^http://sadl.org/RequestAggregator.sadl#vi^var14P| |translator generated name for vi of var14P|)

(defdata |translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator| (enum '(|http://sadl.org/RequestAggregator.sadl#Plan| )))
(deffconst |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALS*| (quote-all |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALUES*|))
(displayname |http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator| |plan of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregator|)
(displayname |http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregatorP| |plan of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregatorP|)
(displayname |translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator| |translator generated name for plan of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregator|)
(displayname |translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregatorP| |translator generated name for plan of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregatorP|)
(displayname |*http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALS*| |*plan of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregator-VALS*|)
(displayname |*http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALUES*| |*plan of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregator-VALUES*|)
(displayname |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALS*| |*translator generated name for plan of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregator-VALS*|)
(displayname |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALUES*| |*translator generated name for plan of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregator-VALUES*|)

(defdata |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var3| (enum '(|http://www.w3.org/2001/XMLSchema#string| )))
(deffconst |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var3-VALS*| (quote-all |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var3-VALUES*|))
(displayname |http://sadl.org/RequestAggregator.sadl#mID^var3| |mID of var3|)
(displayname |http://sadl.org/RequestAggregator.sadl#mID^var3P| |mID of var3P|)
(displayname |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var3| |translator generated name for mID of var3|)
(displayname |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var3P| |translator generated name for mID of var3P|)
(displayname |*http://sadl.org/RequestAggregator.sadl#mID^var3-VALS*| |*mID of var3-VALS*|)
(displayname |*http://sadl.org/RequestAggregator.sadl#mID^var3-VALUES*| |*mID of var3-VALUES*|)
(displayname |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var3-VALS*| |*translator generated name for mID of var3-VALS*|)
(displayname |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var3-VALUES*| |*translator generated name for mID of var3-VALUES*|)

(defdata |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator| (enum '(|http://www.w3.org/2001/XMLSchema#string| )))
(deffconst |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALS*| (quote-all |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALUES*|))
(displayname |http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator| |mID of RoutePlanGeneratedMsg of receive2 of ReqAggregator|)
(displayname |http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregatorP| |mID of RoutePlanGeneratedMsg of receive2 of ReqAggregatorP|)
(displayname |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator| |translator generated name for mID of RoutePlanGeneratedMsg of receive2 of ReqAggregator|)
(displayname |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregatorP| |translator generated name for mID of RoutePlanGeneratedMsg of receive2 of ReqAggregatorP|)
(displayname |*http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALS*| |*mID of RoutePlanGeneratedMsg of receive2 of ReqAggregator-VALS*|)
(displayname |*http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALUES*| |*mID of RoutePlanGeneratedMsg of receive2 of ReqAggregator-VALUES*|)
(displayname |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALS*| |*translator generated name for mID of RoutePlanGeneratedMsg of receive2 of ReqAggregator-VALS*|)
(displayname |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALUES*| |*translator generated name for mID of RoutePlanGeneratedMsg of receive2 of ReqAggregator-VALUES*|)

(defdata |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var9| (enum '(|http://www.w3.org/2001/XMLSchema#string| )))
(deffconst |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var9-VALS*| (quote-all |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var9-VALUES*|))
(displayname |http://sadl.org/RequestAggregator.sadl#mID^var9| |mID of var9|)
(displayname |http://sadl.org/RequestAggregator.sadl#mID^var9P| |mID of var9P|)
(displayname |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var9| |translator generated name for mID of var9|)
(displayname |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var9P| |translator generated name for mID of var9P|)
(displayname |*http://sadl.org/RequestAggregator.sadl#mID^var9-VALS*| |*mID of var9-VALS*|)
(displayname |*http://sadl.org/RequestAggregator.sadl#mID^var9-VALUES*| |*mID of var9-VALUES*|)
(displayname |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var9-VALS*| |*translator generated name for mID of var9-VALS*|)
(displayname |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var9-VALUES*| |*translator generated name for mID of var9-VALUES*|)

(defdata |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator| (enum '(|http://www.w3.org/2001/XMLSchema#string| )))
(deffconst |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALS*| (quote-all |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALUES*|))
(displayname |http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator| |mID of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregator|)
(displayname |http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregatorP| |mID of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregatorP|)
(displayname |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator| |translator generated name for mID of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregator|)
(displayname |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregatorP| |translator generated name for mID of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregatorP|)
(displayname |*http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALS*| |*mID of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregator-VALS*|)
(displayname |*http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALUES*| |*mID of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregator-VALUES*|)
(displayname |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALS*| |*translator generated name for mID of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregator-VALS*|)
(displayname |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator-VALUES*| |*translator generated name for mID of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregator-VALUES*|)

(defdata |translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)| (enum '(|http://sadl.org/RequestAggregator.sadl#Plan| )))
(deffconst |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)-VALS*| (quote-all |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)-VALUES*|))
(displayname |http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)| |plan of (element rareq2_yindex of vi of var14)|)
(displayname |http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)P| |plan of (element rareq2_yindex of vi of var14)P|)
(displayname |translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)| |translator generated name for plan of (element rareq2_yindex of vi of var14)|)
(displayname |translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)P| |translator generated name for plan of (element rareq2_yindex of vi of var14)P|)
(displayname |*http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)-VALS*| |*plan of (element rareq2_yindex of vi of var14)-VALS*|)
(displayname |*http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)-VALUES*| |*plan of (element rareq2_yindex of vi of var14)-VALUES*|)
(displayname |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)-VALS*| |*translator generated name for plan of (element rareq2_yindex of vi of var14)-VALS*|)
(displayname |*translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)-VALUES*| |*translator generated name for plan of (element rareq2_yindex of vi of var14)-VALUES*|)

(defrequirement R3_instance_1
  (    (|rareq2_yindex| |translator_generated_name^rareq2_yindexP|)
    (|http://sadl.org/RequestAggregator.sadl#vi^var14| |translator_generated_name^http://sadl.org/RequestAggregator.sadl#vi^var14P|)
    (|http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator| |translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregatorP|)
    (|http://sadl.org/RequestAggregator.sadl#mID^var3| |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var3P|)
    (|http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator| |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregatorP|)
    (|http://sadl.org/RequestAggregator.sadl#mID^var9| |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^var9P|)
    (|http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator| |translator_generated_name^http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregatorP|)
  )
  (    (|http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)| |translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)P|)
  )
(rimplies (and (equal |http://sadl.org/RequestAggregator.sadl#mID^var3| |http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator|) (equal |http://sadl.org/RequestAggregator.sadl#mID^var9| |http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator|)) (equal |http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)| |http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator|)))

(SRL-meta-data 
  requirement-history 
  ((:SRL-name R3)
   (:Context 2)
   (:transformations ((normalization head R3_instance_0) (grounding R3_instance_1)))
   (:RA-name R3_instance_1)
   (:ModelGenFile "")
   (:VarMapFile "")
      (:Variables ((
                  (:name |http://sadl.org/RequestAggregator.sadl#vi^var14|)
                  (:display-name |vi of var14|)
                  (:SRL-names (|vi of var14|))
                  (:direction monitored)
                  (:type list)
                  (:min-length 1)
                  (:max-length 10)
                  (:event-variable? nil)
                  (:no-contingency-checking? nil)
                  )
                  (
                  (:name |http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator|)
                  (:display-name |plan of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregator|)
                  (:SRL-names (|plan of vpm of RoutePlanGeneratedMsg|))
                  (:direction monitored)
                  (:type enum)
                  (:event-variable? nil)
                  (:no-contingency-checking? t)
                  )
                  (
                  (:name |http://sadl.org/RequestAggregator.sadl#mID^var3|)
                  (:display-name |mID of var3|)
                  (:SRL-names (|mID of var3|))
                  (:direction monitored)
                  (:type string)
                  (:functional-max :unspecified)
                  (:functional-min :unspecified)
                  (:tolerance :unspecified)
                  (:resolution :unspecified)
                  (:event-variable? nil)
                  (:no-contingency-checking? nil)
                  )
                  (
                  (:name |http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator|)
                  (:display-name |mID of RoutePlanGeneratedMsg of receive2 of ReqAggregator|)
                  (:SRL-names (|mID of RoutePlanGeneratedMsg|))
                  (:direction monitored)
                  (:type string)
                  (:functional-max :unspecified)
                  (:functional-min :unspecified)
                  (:tolerance :unspecified)
                  (:resolution :unspecified)
                  (:event-variable? nil)
                  (:no-contingency-checking? nil)
                  )
                  (
                  (:name |http://sadl.org/RequestAggregator.sadl#mID^var9|)
                  (:display-name |mID of var9|)
                  (:SRL-names (|mID of var9|))
                  (:direction monitored)
                  (:type string)
                  (:functional-max :unspecified)
                  (:functional-min :unspecified)
                  (:tolerance :unspecified)
                  (:resolution :unspecified)
                  (:event-variable? nil)
                  (:no-contingency-checking? nil)
                  )
                  (
                  (:name |http://sadl.org/RequestAggregator.sadl#mID^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator|)
                  (:display-name |mID of VehiclePlanInfo of vpm of RoutePlanGeneratedMsg of receive2 of ReqAggregator|)
                  (:SRL-names (|mID of vpm of RoutePlanGeneratedMsg|))
                  (:direction monitored)
                  (:type string)
                  (:functional-max :unspecified)
                  (:functional-min :unspecified)
                  (:tolerance :unspecified)
                  (:resolution :unspecified)
                  (:event-variable? nil)
                  (:no-contingency-checking? nil)
                  )
                  (
                  (:name |http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)|)
                  (:display-name |plan of (element rareq2_yindex of vi of var14)|)
                  (:SRL-names (|plan of (element rareq2_yindex of vi of var14)|))
                  (:direction controlled)
                  (:type enum)
                  (:event-variable? nil)
                  (:no-contingency-checking? t)
                  )))
  )
)

(SRL-meta-data 
  context 
  ((:context-id 2)
   (:exp (|ReqAggregator with receive2 RoutePlanGeneratedMsg|))))







(SRL-meta-data 
  no-contingency-checking-register 
  ((:name |translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^http://sadl.org/RequestAggregator.sadl#VehiclePlanInfo^http://sadl.org/RequestAggregator.sadl#vpm^http://sadl.org/RequestAggregator.sadl#RoutePlanGeneratedMsg^http://sadl.org/RequestAggregator.sadl#receive2^http://sadl.org/RequestAggregator.sadl#ReqAggregator|)))

(SRL-meta-data 
  no-contingency-checking-register 
  ((:name |translator_generated_name^http://sadl.org/RequestAggregator.sadl#plan^(nth-element ^^^rareq2_yindex^^^ ^^^http://sadl.org/RequestAggregator.sadl#vi^var14^^^)|)))

