% Prolog file generated by SADL SRL (.sreq) Plug-in, 2017-10-19 14:04:55
% Generated from SADL Requirements model with uri 'http://sadl.org/RA-Req3.sreq', with alias 'rareq3', with corresponding SRL (.sreq) file 'RA-Req3.sreq'

:- style_check(-atom).

rce_version('2.0.0.201702021432').

namespace('http://sadl.org/RA-Req3.sreq').
prefix('http://sadl.org/RA-Req3.sreq','rareq3').
prefix('http://sadl.org/test.sadl','test').
prefix('http://sadl.org/RequestAggregator.sadl','RA').

assumption(name('A4'), then(assumesThat('http://sadl.org/RequestAggregator.sadl#ReqAggregator',le('rareq3_xindex',listLength(propertyOfSubject('http://sadl.org/RequestAggregator.sadl#vi',propertyOfSubject('http://sadl.org/RequestAggregator.sadl#rrm','http://sadl.org/RequestAggregator.sadl#RouteRequestMsg'))))))).
assumption(name('A4'), context(and('http://sadl.org/RequestAggregator.sadl#ReqAggregator',is('rareq3_xindex',declaration('http://www.w3.org/2001/XMLSchema#int'))))).
assumption(name('A4'), contextText('ReqAggregator and xindex is an int and xelement is element xindex of requestList of ReqAggregator and viCount is length of vi of xelement')).
assumption(name('A4'), location('/resource/ReqAggregator-v4/Requirement_Model/RA-Req3.sreq',9,116,291)).
assumption(name('A4'), text('Assumption A4: ReqAggregator assumes that xindex <= length of vi of rrm of RouteRequestMsg.')).

assertion(name('A5'), when(gt(propertyOfSubject('http://sadl.org/RequestAggregator.sadl#numPlansPending',*variableReplacement*(xelement)),0))).
assertion(name('A5'), then(assertsThat('http://sadl.org/RequestAggregator.sadl#ReqAggregator',is(propertyOfSubject('http://sadl.org/RequestAggregator.sadl#send2','http://sadl.org/RequestAggregator.sadl#ReqAggregator'),'immaterial')))).
assertion(name('A5'), context(and('http://sadl.org/RequestAggregator.sadl#ReqAggregator',is('rareq3_xindex',declaration('http://www.w3.org/2001/XMLSchema#int'))))).
assertion(name('A5'), contextText('ReqAggregator and xindex is an int and xelement is element xindex of requestList of ReqAggregator and viCount is length of vi of xelement')).
assertion(name('A5'), location('/resource/ReqAggregator-v4/Requirement_Model/RA-Req3.sreq',14,118,411)).
assertion(name('A5'), text('Assertion A5: ReqAggregator asserts that send2 of ReqAggregator is immaterial when numPlansPending of xelement > 0.')).

sreq(name('R4'), when(is(propertyOfSubject('http://sadl.org/RequestAggregator.sadl#numPlansPending',getListElementAt('rareq3_xindex',propertyOfSubject('http://sadl.org/RequestAggregator.sadl#requestList','http://sadl.org/RequestAggregator.sadl#ReqAggregator'))),0))).
sreq(name('R4'), where(decomposition('rareq3_newelement',type('http://sadl.org/RequestAggregator.sadl#RouteGeneratedMsg'),and(property('http://sadl.org/RequestAggregator.sadl#mID',propertyOfSubject('http://sadl.org/RequestAggregator.sadl#mID',getListElementAt('rareq3_xindex',propertyOfSubject('http://sadl.org/RequestAggregator.sadl#requestList','http://sadl.org/RequestAggregator.sadl#ReqAggregator')))),property('http://sadl.org/RequestAggregator.sadl#vehiclePlansInfo',propertyOfSubject('http://sadl.org/RequestAggregator.sadl#vi',getListElementAt('rareq3_xindex',propertyOfSubject('http://sadl.org/RequestAggregator.sadl#requestList','http://sadl.org/RequestAggregator.sadl#ReqAggregator')))))))).
sreq(name('R4'), then(shallSet('http://sadl.org/RequestAggregator.sadl#ReqAggregator',is(propertyOfSubject('http://sadl.org/RequestAggregator.sadl#send2','http://sadl.org/RequestAggregator.sadl#ReqAggregator'),'rareq3_newelement')))).
sreq(name('R4'), context(and('http://sadl.org/RequestAggregator.sadl#ReqAggregator',is('rareq3_xindex',declaration('http://www.w3.org/2001/XMLSchema#int'))))).
sreq(name('R4'), contextText('ReqAggregator and xindex is an int and xelement is element xindex of requestList of ReqAggregator and viCount is length of vi of xelement')).
sreq(name('R4'), location('/resource/ReqAggregator-v4/Requirement_Model/RA-Req3.sreq',17,308,533)).
sreq(name('R4'), text('Requirement R4: ReqAggregator shall set send2 of ReqAggregator to newelement when numPlansPending of xelement = 0 where newelement is (a RouteGeneratedMsg with mID (mID of xelement) with vehiclePlansInfo (vi of element xindex of requestList of ReqAggregator) ).')).

